import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();
  factory LocalizationService() => _instance;
  LocalizationService._internal();

  String _currentLanguage = 'id'; // 'id' or 'en'

  String get currentLanguage => _currentLanguage;
  bool get isEnglish => _currentLanguage == 'en';

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('app_language') ?? 'id';
    notifyListeners();
  }

  Future<void> setLanguage(String langCode) async {
    if (_currentLanguage != langCode) {
      _currentLanguage = langCode;
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('app_language', langCode);
      notifyListeners();
    }
  }

  String translate(String key) {
    final Map<String, Map<String, String>> localizedValues = {
      'id': {
        'netropia': 'Netropia',
        'settings': 'Pengaturan',
        'account': 'Akun',
        'preferences': 'Preferensi',
        'learning': 'Pembelajaran',
        'security': 'Keamanan',
        'edit_name': 'Edit Nama',
        'edit_photo': 'Edit Foto',
        'edit_email': 'Edit Email',
        'change_password': 'Ubah Password',
        'notifications': 'Notifikasi',
        'dark_mode': 'Dark Mode',
        'language': 'Bahasa',
        'indonesian': 'Bahasa Indonesia',
        'english': 'English',
        'learning_reminder': 'Pengingat Belajar',
        'daily_target': 'Target Belajar Harian',
        'streak': 'Streak Belajar',
        'login_session': 'Login Session',
        'logout': 'Keluar',
        'home': 'Beranda',
        'progress': 'Progres',
        'ai': 'AI',
        'simulation': 'Simulasi',
        'profile': 'Profil',
        'study_materials': 'Materi TKJ',
        'study_materials_desc': 'Pelajari materi TKJ',
        'subnet_calculator': 'Kalkulator Subnet',
        'subnet_desc': 'Hitung subnet',
        'device_3d': 'Perangkat 3D',
        'device_3d_desc': 'Eksplorasi alat TKJ',
        'attendance': 'Absensi',
        'attendance_desc': 'Kehadiran belajar',
        'borrowing': 'Peminjaman',
        'borrowing_desc': 'Pinjam alat TKJ',
        'project': 'Project',
        'project_desc': 'Tugas & Project',
        'ai_assistant': 'Netropia AI',
        'ai_assistant_desc': 'Asisten belajar AI',
        'virtual_lab': 'Virtual Lab',
        'virtual_lab_desc': 'Simulasi jaringan',
        'recent_activities': 'Aktivitas Terbaru',
        'see_all': 'Lihat Semua',
        'learning_progress': 'Progress Belajar',
        'continue_learning': 'Lanjutkan Belajar',
        'learning_module': 'Modul Pembelajaran',
        'continue_button': 'Lanjutkan Pembelajaran',
        'welcome_halo': 'Halo, ',
        'welcome_subtitle': 'Semangat belajar, masa depanmu dimulai dari sini.',
        'achievements': 'Pencapaian',
        'edit_profile': 'Edit Profil',
        'help': 'Bantuan',
        'about_netropia': 'Tentang Netropia',
        'mark_all_read': 'Tandai Semua Dibaca',
        'all': 'Semua',
        'no_notifications': 'Belum ada notifikasi',
        'refresh': 'Perbarui Data',
        'badges_prestasi': 'Lencana & Prestasi',
        'activity_history': 'Riwayat Aktivitas',
        'cancel': 'Batal',
        'save': 'Simpan',
        'close': 'Tutup',
        'yes': 'Ya',
        'no': 'Tidak',
        'coming_soon': 'sedang dalam pengembangan.',
        'streak_days': ' Hari Berturut-turut!',
        'streak_desc': 'Hebat! Kamu telah belajar secara konsisten. Pertahankan semangat belajarmu setiap hari untuk menjaga streak!',
        'daily_target_title': 'Target Belajar Harian',
        'daily_target_desc': 'Masukkan target belajar harian kamu dalam menit.',
        'logout_title': 'Keluar Akun',
        'logout_desc': 'Apakah kamu yakin ingin keluar dari aplikasi?',
        'select_language': 'Pilih Bahasa / Select Language',
        'select_materi': 'Pilih Materi',
        'start_materi_desc': 'Mulai dari materi dasar kemudian lanjutkan ke materi berikutnya.',
        'video': 'Video',
        'peta_konsep': 'Peta Konsep',
        'referensi': 'Referensi',
        'pre_test': 'Pre Test',
        'post_test': 'Post Test',
        'penugasan': 'Penugasan',
        'portofolio': 'Portofolio',
        'forum_diskusi': 'Forum Diskusi',
        'refleksi': 'Refleksi',
        'evaluasi': 'Evaluasi',
        'feedback': 'Feedback',
        'ask_ai_placeholder': 'Tanyakan tentang materi TKJ...',
        'ai_greeting': 'Halo! Saya Netropia AI. Ada yang ingin kamu tanyakan?',
        'lab_simulation': 'Simulasi Virtual Lab',
        'overall_progress': 'Total Progres',
        'quiz_scores': 'Nilai Kuis',
        'active_projects': 'Project Aktif',
        'scan_qr': 'Scan QR Code',
        'input_code': 'Masukkan Kode',
        'borrow_tool': 'Pinjam Alat',
        'return_tool': 'Kembalikan Alat',
        'calculate_subnet': 'Hitung Subnet',
        'results': 'Hasil Perhitungan',
        'help_support': 'Bantuan & Dukungan',
        'about_app': 'Tentang Aplikasi',
      },
      'en': {
        'netropia': 'Netropia',
        'settings': 'Settings',
        'account': 'Account',
        'preferences': 'Preferences',
        'learning': 'Learning',
        'security': 'Security',
        'edit_name': 'Edit Name',
        'edit_photo': 'Edit Photo',
        'edit_email': 'Edit Email',
        'change_password': 'Change Password',
        'notifications': 'Notifications',
        'dark_mode': 'Dark Mode',
        'language': 'Language',
        'indonesian': 'Bahasa Indonesia',
        'english': 'English',
        'learning_reminder': 'Learning Reminder',
        'daily_target': 'Daily Learning Target',
        'streak': 'Learning Streak',
        'login_session': 'Login Session',
        'logout': 'Logout',
        'home': 'Home',
        'progress': 'Progress',
        'ai': 'AI',
        'simulation': 'Simulation',
        'profile': 'Profile',
        'study_materials': 'TKJ Materials',
        'study_materials_desc': 'Study TKJ materials',
        'subnet_calculator': 'Subnet Calculator',
        'subnet_desc': 'Calculate subnets',
        'device_3d': '3D Devices',
        'device_3d_desc': 'Explore TKJ tools',
        'attendance': 'Attendance',
        'attendance_desc': 'Learning attendance',
        'borrowing': 'Borrowing',
        'borrowing_desc': 'Borrow TKJ tools',
        'project': 'Projects',
        'project_desc': 'Tasks & Projects',
        'ai_assistant': 'Netropia AI',
        'ai_assistant_desc': 'AI learning assistant',
        'virtual_lab': 'Virtual Lab',
        'virtual_lab_desc': 'Network simulation',
        'recent_activities': 'Recent Activities',
        'see_all': 'See All',
        'learning_progress': 'Learning Progress',
        'continue_learning': 'Continue Learning',
        'learning_module': 'Learning Module',
        'continue_button': 'Continue Learning',
        'welcome_halo': 'Hello, ',
        'welcome_subtitle': 'Keep learning, your future starts here.',
        'achievements': 'Achievements',
        'edit_profile': 'Edit Profile',
        'help': 'Help',
        'about_netropia': 'About Netropia',
        'mark_all_read': 'Mark All as Read',
        'all': 'All',
        'no_notifications': 'No notifications yet',
        'refresh': 'Refresh Data',
        'badges_prestasi': 'Badges & Achievements',
        'activity_history': 'Activity History',
        'cancel': 'Cancel',
        'save': 'Save',
        'close': 'Close',
        'yes': 'Yes',
        'no': 'No',
        'coming_soon': 'is under development.',
        'streak_days': ' Days in a Row!',
        'streak_desc': 'Great! You have been learning consistently. Keep up your learning spirit every day to maintain your streak!',
        'daily_target_title': 'Daily Learning Target',
        'daily_target_desc': 'Enter your daily learning target in minutes.',
        'logout_title': 'Logout Account',
        'logout_desc': 'Are you sure you want to log out from the app?',
        'select_language': 'Select Language / Pilih Bahasa',
        'select_materi': 'Select Material',
        'start_materi_desc': 'Start from basic materials then proceed to the next module.',
        'video': 'Video',
        'peta_konsep': 'Concept Map',
        'referensi': 'Reference',
        'pre_test': 'Pre Test',
        'post_test': 'Post Test',
        'penugasan': 'Assignment',
        'portofolio': 'Portfolio',
        'forum_diskusi': 'Discussion Forum',
        'refleksi': 'Reflection',
        'evaluasi': 'Evaluation',
        'feedback': 'Feedback',
        'ask_ai_placeholder': 'Ask anything about TKJ materials...',
        'ai_greeting': 'Hello! I am Netropia AI. Do you have any questions?',
        'lab_simulation': 'Virtual Lab Simulation',
        'overall_progress': 'Overall Progress',
        'quiz_scores': 'Quiz Scores',
        'active_projects': 'Active Projects',
        'scan_qr': 'Scan QR Code',
        'input_code': 'Enter Code',
        'borrow_tool': 'Borrow Tool',
        'return_tool': 'Return Tool',
        'calculate_subnet': 'Calculate Subnet',
        'results': 'Calculation Results',
        'help_support': 'Help & Support',
        'about_app': 'About Application',
      },
    };

    return localizedValues[_currentLanguage]?[key] ?? localizedValues['id']?[key] ?? key;
  }
}

final localizationService = LocalizationService();
