// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhB8yOkmChtMFbXg5ZMzX8kbCF0-CLIds',
    appId: '1:641151113525:web:3cd6e75238693061e8147c',
    messagingSenderId: '641151113525',
    projectId: 'netropia-tkj',
    authDomain: 'netropia-tkj.firebaseapp.com',
    storageBucket: 'netropia-tkj.firebasestorage.app',
    measurementId: 'G-KP0CB2KRKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBseGwZ2jVs89y6en7DSunBiAJKN49nqdE',
    appId: '1:641151113525:android:b4024247b84383b6e8147c',
    messagingSenderId: '641151113525',
    projectId: 'netropia-tkj',
    storageBucket: 'netropia-tkj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQbWlXaG0NfGXo9F7TiplVPe5QYcijsRQ',
    appId: '1:641151113525:ios:11133696a0aa273ee8147c',
    messagingSenderId: '641151113525',
    projectId: 'netropia-tkj',
    storageBucket: 'netropia-tkj.firebasestorage.app',
    iosBundleId: 'com.example.netropia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQbWlXaG0NfGXo9F7TiplVPe5QYcijsRQ',
    appId: '1:641151113525:ios:11133696a0aa273ee8147c',
    messagingSenderId: '641151113525',
    projectId: 'netropia-tkj',
    storageBucket: 'netropia-tkj.firebasestorage.app',
    iosBundleId: 'com.example.netropia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhB8yOkmChtMFbXg5ZMzX8kbCF0-CLIds',
    appId: '1:641151113525:web:7157ede962bc42e5e8147c',
    messagingSenderId: '641151113525',
    projectId: 'netropia-tkj',
    authDomain: 'netropia-tkj.firebaseapp.com',
    storageBucket: 'netropia-tkj.firebasestorage.app',
    measurementId: 'G-7N28MVD303',
  );
}
