import 'package:flutter/material.dart';
import 'utp_stp_screen.dart';

class JenisKabelScreen extends StatelessWidget {
  const JenisKabelScreen({super.key});
  static const Color primaryBrown = Color(0xFF5D4037); static const Color darkBrown = Color(0xFF3E2723); static const Color lightBrown = Color(0xFFF3ECE9); static const Color textDark = Color(0xFF263238); static const Color textGrey = Color(0xFF607D8B); static const Color borderGrey = Color(0xFFDCE3EA);
  @override Widget build(BuildContext context) => Scaffold(backgroundColor: const Color(0xFFF7F9FB), appBar: _bar(), body: SafeArea(child: SingleChildScrollView(padding: const EdgeInsets.fromLTRB(20,24,20,32), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_head(), const SizedBox(height:26), _card(Icons.cable, 'UTP / STP', 'Kabel twisted pair yang banyak digunakan pada jaringan Ethernet. Memiliki pasangan kawat yang dipilin untuk membantu mengurangi interferensi.', 'Umum pada LAN'), _card(Icons.settings_input_component, 'Coaxial', 'Kabel dengan konduktor di tengah dan lapisan pelindung. Banyak dijumpai pada sistem lama, TV kabel, dan penggunaan tertentu.', 'Penggunaan khusus'), _card(Icons.wb_sunny_outlined, 'Fiber Optic', 'Mengirimkan data menggunakan cahaya melalui serat optik. Cocok untuk jarak jauh dan kebutuhan bandwidth tinggi.', 'Kecepatan & jarak tinggi'), const SizedBox(height:24), _comparison(), const SizedBox(height:28), _nav(context)]))));
  PreferredSizeWidget _bar()=>AppBar(backgroundColor:Colors.white,foregroundColor:textDark,elevation:0,scrolledUnderElevation:0,leading:Builder(builder:(context)=>IconButton(icon:const Icon(Icons.arrow_back_rounded),onPressed:()=>Navigator.pop(context))),title:const Text('Kabel Jaringan',style:TextStyle(fontSize:17,fontWeight:FontWeight.w700)),actions:[_badge('02 / 08')],bottom:_progress(.25));
  PreferredSize _progress(double v)=>PreferredSize(preferredSize:const Size.fromHeight(3),child:Container(height:3,alignment:Alignment.centerLeft,child:FractionallySizedBox(widthFactor:v,child:Container(color:primaryBrown))));
  Widget _badge(String t)=>Container(margin:const EdgeInsets.only(right:16),padding:const EdgeInsets.symmetric(horizontal:10,vertical:6),decoration:BoxDecoration(color:lightBrown,borderRadius:BorderRadius.circular(8)),child:Text(t,style:const TextStyle(color:primaryBrown,fontSize:12,fontWeight:FontWeight.w700)));
  Widget _head()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:5),decoration:BoxDecoration(color:primaryBrown,borderRadius:BorderRadius.circular(6)),child:const Text('MATERI 02',style:TextStyle(color:Colors.white,fontSize:11,fontWeight:FontWeight.w700))),const SizedBox(height:14),const Text('Jenis-Jenis Kabel\nJaringan',style:TextStyle(color:darkBrown,fontSize:29,fontWeight:FontWeight.w800,height:1.12)),const SizedBox(height:12),const Text('Mengenal karakteristik media kabel yang umum digunakan dalam jaringan komputer.',style:TextStyle(color:textGrey,fontSize:15,height:1.55))]);
  Widget _card(IconData icon,String title,String desc,String tag)=>Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,border:Border.all(color:borderGrey),borderRadius:BorderRadius.circular(12)),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:48,height:48,decoration:BoxDecoration(color:lightBrown,borderRadius:BorderRadius.circular(10)),child:Icon(icon,color:primaryBrown)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(title,style:const TextStyle(color:textDark,fontSize:15,fontWeight:FontWeight.w800))),Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:4),decoration:BoxDecoration(color:lightBrown,borderRadius:BorderRadius.circular(20)),child:Text(tag,style:const TextStyle(color:primaryBrown,fontSize:9,fontWeight:FontWeight.w700)))]),const SizedBox(height:7),Text(desc,style:const TextStyle(color:textGrey,fontSize:12.5,height:1.5))]))]));
  Widget _comparison()=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:darkBrown,borderRadius:BorderRadius.circular(12)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('CARA MEMILIH',style:TextStyle(color:Colors.white70,fontSize:10,fontWeight:FontWeight.w700,letterSpacing:1)),const SizedBox(height:9),_row('LAN kelas/lab','UTP atau STP'),_row('Lingkungan rawan gangguan','STP'),_row('Jarak jauh','Fiber optic') ]));
  Widget _row(String a,String b)=>Padding(padding:const EdgeInsets.only(bottom:8),child:Row(children:[Expanded(child:Text(a,style:const TextStyle(color:Colors.white,fontSize:12))),const Icon(Icons.arrow_forward_rounded,color:Colors.white38,size:15),const SizedBox(width:8),Text(b,style:const TextStyle(color:Colors.white,fontSize:12,fontWeight:FontWeight.w700))]));
  Widget _nav(BuildContext context)=>Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()=>Navigator.pop(context),icon:const Icon(Icons.arrow_back_rounded,size:18),label:const Text('Sebelumnya'),style:OutlinedButton.styleFrom(minimumSize:const Size(0,48),foregroundColor:textGrey,side:const BorderSide(color:borderGrey)))),const SizedBox(width:12),Expanded(child:ElevatedButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const UtpStpScreen())),icon:const Icon(Icons.arrow_forward_rounded,size:18),label:const Text('Berikutnya'),style:ElevatedButton.styleFrom(minimumSize:const Size(0,48),backgroundColor:primaryBrown,foregroundColor:Colors.white,elevation:0))) ]);
}
